version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/code"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "cargo"
    open-pull-requests-limit: 10
    target-branch: "main"
