name: Release

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Release the kraken
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix : 
        os: [ubuntu-latest]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2          
      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Upload Lambda function
        shell: bash
        run: |
          zip lambda.zip target/release/tm-notify
          aws s3api put-object --key release/latest.zip --bucket cdkstack-tmnotifytmnotifyassetsd39db889-1eao6gzvjr848 --body lambda.zip
